export const genresEnum = [
    "Fiction",
    "Mystery",
    "Thriller",
    "Science Fiction",
    "Fantasy",
    "Horror",
    "Historical Fiction",
    "Romance",
    "Adventure",
    "Action",
    "Dystopian",
    "Comedy",
    "Satire",
    "Drama",
    "Poetry",
    "Non-fiction",
    "Biography",
    "Autobiography",
    "Memoir",
    "Self-help",
    "Business",
    "Finance",
    "Psychology",
    "Philosophy",
    "Science",
    "Technology",
    "History",
    "Politics",
    "Sociology",
    "Anthropology",
    "Mystery",
    "Crime",
    "Detective",
    "Espionage",
    "Legal",
    "Medical",
    "Political thriller",
    "Spy thriller",
    "War/Military",
    "Western",
    "Coming-of-age",
    "Family drama",
    "Children's",
    "Middle-grade",
    "Young Adult (YA)",
    "New Adult (NA)",
    "Religious/Inspirational",
    "Fantasy Romance",
    "Paranormal Romance",
    "Historical Romance",
    "Contemporary Romance",
    "LGBTQ+",
    "Women's Fiction",
    "Chick Lit",
    "Urban Fantasy",
    "Epic Fantasy",
    "High Fantasy",
    "Alternate History",
    "Steampunk",
    "Cyberpunk",
    "Post-apocalyptic",
    "Space Opera",
    "Hard Science Fiction",
    "Soft Science Fiction",
    "Humor",
    "Satire",
    "Farce",
    "Tragedy",
    "Historical Non-fiction",
    "True Crime",
    "Science and Nature",
    "Travel",
    "Food and Cooking",
    "Art and Photography",
    "Music",
    "Sports and Recreation",
  ];